---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: https://pkc-YOURCLUSTER.confluent.cloud:443
    kafkaClusterID: lkc-ID
    authentication:
      type: basic
      basic:
        secretRef: cloud-rest-access
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: users
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: https://pkc-YOURCLUSTER.confluent.cloud:443
    kafkaClusterID: lkc-ID
    authentication:
      type: basic
      basic:
        secretRef: cloud-rest-access
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: https://pkc-YOURCLUSTER.confluent.cloud:443
    kafkaClusterID: lkc-ID
    authentication:
      type: basic
      basic:
        secretRef: cloud-rest-access                