apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: cloud-demo-topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: https://YOURCLUSTERR.confluent.cloud:443
    kafkaClusterID: lkc-ID
    authentication:
      type: basic
      basic:
        secretRef: cloud-rest-access